force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>EVT - {000000}</displayFormat>
        <label>Event #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Live?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DeleteEventBatch.cls
public class DeleteEventBatch implements Database.Batchable<sObject> {
	
    public Database.QueryLocator start(Database.BatchableContext batchContext) {
        // Query to locate related data
        String Query = 'Select Id, Name From Event__c Where Live__c = true AND End_Date_Time__c < LAST_N_MONTHS:2';
        return Database.getQueryLocator(Query);
    }
    
    public void execute(Database.BatchableContext batchContext, List<Event__c> eventlist) {
        if(!eventList.isEmpty()){
            List<Database.DeleteResult> deleteResult = Database.delete(eventlist);
            for (Database.DeleteResult dr : deleteResult){
                if (!dr.isSuccess()){
                    List<Database.Error> errors = dr.getErrors();
                    String stringError = String.join(errors, ',');
                    TransactionLogHandler.doHandleExceptionwithError(stringError, 'DeleteEventBatch');
                }
            }
        }
    }
    
    public void finish(Database.BatchableContext batchContext) {
        /*
        //Send email to administrator
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject('Batch Deletion Completed');
        List<string> toAddress =  new List<String>();
        toAddress.add('shin_bamba@adoc.co.jp');
        mail.setToAddresses( toAddress );
        mail.setSenderDisplayName('Bamba Shin');
        
        mail.setHtmlBody('The DeleteEventBatch Batch Prcoessing has been completed');
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage> {mail};
        Messaging.sendEmail(emails);
		*/
    }
}